api = "0.10"

[[targets]]
os = "linux"

[buildpack]
id = "ricket-son/oras"
version = "0.2.0"
name = "ORAS Buildpack"
homepage = "https://github.com/ricket-son/buildpacks-oras"
description = "A buildpack that provides ORAS."

[[stacks]]
id = "*"